# Generated by Django 5.1.1 on 2024-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancers',
            name='bio',
            field=models.TextField(),
        ),
    ]
